[package]
name = "riscv"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_field = "0.10.1"

[build-dependencies]
cfg_aliases = "0.1"
